### ISSUE TITLE
Update company list

### ISSUE THREAD

**Issue by jwied** [interregna/arraylanguage-companies#14]
Please add the following new entry to the list of companies, that work with array languages:
Name: DPC
Language: APL
Location: Germany
Sector:  consulting + software dev
Source:    https://dpc.de/
Remote OK?   Yes

**Comment by abrudz** [comment]
I've updated the list. Btw, if you seek to hire APLers, you can add an entry to [apl.wiki/Job_listings](https://apl.wiki/Job_listings) (or ask me to do so).
